//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mocha.Web {
	
	
	public partial class InstancePage {

		protected System.Web.UI.WebControls.Panel pnlDashboard;

		protected System.Web.UI.WebControls.Panel pnlDashboardEmpty;
		
		protected System.Web.UI.WebControls.Panel pnlPageBuilder;
		
		protected System.Web.UI.WebControls.Panel pnlDashboardContent;

		protected System.Web.UI.WebControls.Panel pnlPageFooterButtons;

		protected System.Web.UI.WebControls.Label label;
		
		protected System.Web.UI.WebControls.Panel pnlApplications;
		
		protected System.Web.UI.WebControls.Panel pnlTroubleTickets;
		
		protected System.Web.UI.WebControls.Panel pnlObjects;

		protected System.Web.UI.WebControls.Panel pnlClass;

		protected System.Web.UI.WebControls.Panel pnlTask;

		protected System.Web.UI.WebControls.Panel pnlElementContent;

		protected System.Web.UI.WebControls.Panel pnlMethodBinding;

		protected System.Web.UI.WebControls.Panel pnlTestMethodBinding;

		protected System.Web.UI.WebControls.Panel pnlTestMethodBindingReturned;

		protected MBS.Web.Controls.FormView fvMethodDefinition;

		protected MBS.Web.Controls.FormView fvMethodParms;

		protected MBS.Web.Controls.FormView fvMethodReturn;

		protected MBS.Web.Controls.FormView fvMethodBindingDefinition;

		protected System.Web.UI.WebControls.Panel pnlMethod;

		protected System.Web.UI.WebControls.Content aspcPageFooter;
		
		protected System.Web.UI.WebControls.Button cmdPageFooterOK;

		protected MBS.Web.Controls.FormView fvStructure;

		protected MBS.Web.Controls.FormView fvInheritance;

		protected MBS.Web.Controls.FormView fvTestMethodBinding;

		protected MBS.Web.Controls.FormView fvTestMethodBindingParameters;

		protected MBS.Web.Controls.FormView fvElementContent;

		protected MBS.Web.Controls.ListView lvAttributes;

		protected MBS.Web.Controls.ListView lvInstances;

		protected MBS.Web.Controls.ListView lvRelationships;

		protected MBS.Web.Controls.ListView lvMethodBindingParameters;

		protected MBS.Web.Controls.ListView lvElementContentDerivedValidations;

		protected System.Web.UI.WebControls.Panel pnlMethodImplementationGRA;

		protected System.Web.UI.WebControls.Panel pnlMethodImplementationSAC;

		protected Mocha.Web.Controls.InstanceBrowser ibTestMethodBinding;

		public new Mocha.Web.MasterPages.Default Master {
			get {
				return ((Mocha.Web.MasterPages.Default)(base.Master));
			}
		}
	}
}
