//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mocha.Web {
	
	
	public partial class UML {
		
		public new Mocha.Web.MasterPages.Default Master {
			get {
				return ((Mocha.Web.MasterPages.Default)(base.Master));
			}
		}
	}
}
