//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mocha.Web {
	
	
	public partial class InstancePage {
		
		protected System.Web.UI.WebControls.Panel pnlDashboard;
		
		protected System.Web.UI.WebControls.Panel pnlDashboardContent;
		
		protected System.Web.UI.WebControls.Label label;
		
		protected System.Web.UI.WebControls.Panel pnlApplications;
		
		protected System.Web.UI.WebControls.Panel pnlTroubleTickets;
		
		protected System.Web.UI.WebControls.Panel pnlObjects;
		
		protected System.Web.UI.WebControls.Panel pnlTask;
		
		public new Mocha.Web.MasterPages.Default Master {
			get {
				return ((Mocha.Web.MasterPages.Default)(base.Master));
			}
		}
	}
}
