//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mocha.Web.MasterPages {
	
	
	public partial class Blank {
		
		protected System.Web.UI.WebControls.ContentPlaceHolder aspcBeforeContent;
		
		protected System.Web.UI.WebControls.ContentPlaceHolder aspcBeforePageContent;
		
		protected System.Web.UI.WebControls.Panel OMSUnavailable;
		
		protected System.Web.UI.WebControls.ContentPlaceHolder aspcContent;
		
		protected System.Web.UI.WebControls.ContentPlaceHolder aspcAfterPageContent;
		
		protected System.Web.UI.WebControls.ContentPlaceHolder aspcAfterContent;
	}
}
