//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mocha.Web.MasterPages {
	
	
	public partial class Default {
		
		protected System.Web.UI.WebControls.Label lblTaskTitle;
		
		protected System.Web.UI.WebControls.LinkButton lblTaskObject;
		
		protected System.Web.UI.WebControls.Label lblTaskSubtitle;
		
		protected System.Web.UI.WebControls.ContentPlaceHolder aspcContent;
		
		protected System.Web.UI.WebControls.Label lblLegalNoticeText;
		
		protected System.Web.UI.WebControls.Label lblSystemVersion;
		
		protected System.Web.UI.WebControls.Label lblTenantName;
		
		public new Mocha.Web.MasterPages.Blank Master {
			get {
				return ((Mocha.Web.MasterPages.Blank)(base.Master));
			}
		}
	}
}
